version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/test/admin_report/
permissions:
   - object: /var/www/test/admin_report/
     pattern: "**"
     owner: root
     group: root
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: script/installapache.sh
      runas: root
   AfterInstall:
    - location: script/restartapache.sh
      runas: root
    - location: script/startapache.sh
      runas: root
